### PR TITLE
Fix boundary assertions

### LINKED ISSUE #73: Property values should not be matched by \b
See following example:
```css
@keyframes line-scale {
}
#test {
  animation: line-scale;
}
```
`: line-scale;` generates:
```html
<span class="meta property-value css">
  <span class="punctuation separator key-value css">:</span>
  <span class="support constant property-value css">line</span>
  -scale
  <span class="punctuation terminator rule css">;</span>
</span>
```
For `line` is a [constant property-value](https://github.com/atom/language-css/blob/d0595beab2745d80bb7bfb180002d0baa2a1b030/grammars/css.cson#L372) and `\b` regrads `-` as a word boundary, it goes wrong.
Same issue with [constant font-name](https://github.com/atom/language-css/blob/d0595beab2745d80bb7bfb180002d0baa2a1b030/grammars/css.cson#L376).
ES5 doesn't support lookbehind assertions, I'm not sure how to solve it.
Maybe property-values should match [`<ident-token>`](https://drafts.csswg.org/css-syntax-3/#ident-token-diagram) first and then constant property-value?

### PR DESCRIPTION
**Pull request by esdoppio**
fix #73

### CODE REVIEW

**Comment by 50Wliu** [comment]
Tests please.

**Comment by weizhenye** [comment]
I'm curious about how regular expressions work in `cson` file (or CoffeeScript), are they executed directly by JavaScript finally?
I was thought lookbehind assertions are not supported in ES5, so things like `(?<![\\w-])` would not work. But now I found it just works (Atom v1.8.0).
It seems [V8 4.9 supports lookbehind assertions](https://v8project.blogspot.bg/2016/02/regexp-lookbehind-assertions.html) by `--harmony`, is Atom using it? What about Atom that using old version V8?

**Comment by esdoppio** [comment]
https://github.com/atom/atom/blob/master/package.json#L46

**Comment by esdoppio** [comment]
@50Wliu Anything else?

**Comment by weizhenye** [comment]
@esdoppio Thanks.

**Pull request merged**
