### PR TITLE
Web Components & Flexbox

### PR DESCRIPTION
**Pull request by silvenon**
Web Components pseudo elements: `::host`, `::content`.

Flexbox properties: `align-items`, `align-content`, `justify-content`, `align-self`, `flex-flow`, `flex-wrap`, `flex-direction`, `flex-basis`, `flex-grow`, `flex-shrink`.

Flexbox values: `flex`, `flex-start`, `flex-end`, `space-around`, `space-between`, `stretch`, `column`, `column-reverse`, `row`, `row-reverse`, `wrap`, `wrap-reverse`.

Bonus: support for prefixed `::selection`.

### CODE REVIEW

**Comment by silvenon** [comment]
There's a conflict. Tell me when and if you're ready to merge, and I'll rebase :wink:

**Comment by mnquintana** [comment]
It would actually be a lot easier to review if you rebased first - thanks!

**Comment by simurai** [comment]
It probably conflicts with the already merged flexbox PR #27.

The Web Components pseudo elements and prefixed `::selection` would still be a good addition.

**Comment by kevinsawicki** [comment]
Closing this out for now, please comment once the conflicts have been resolved and this branch is mergeable again and we can review it then.

**Comment by silvenon** [comment]
This branch is mergeable again. If you reopen will my (force) pushed commits be visible here?

**Comment by kevinsawicki** [comment]
> If you reopen will my (force) pushed commits be visible here?

Looks like the reopen button is disabled, mind creating a new pull request, sorry about this.

**Comment by silvenon** [comment]
Sure (#36). I think that's because I force pushed before reopening.

**Pull request closed without merging**
