### PR TITLE
Add CSS scrollbars new properties and values

### PR DESCRIPTION
**Pull request by pascalduez**
### Description of the Change

Added new property keywords and names to support CSS scrollbars.
See https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars

### CODE REVIEW

**Comment by rsese** [comment]
Thanks for the contribution!

Looks like this is still a draft but with only Firefox support - as far as I know, we would wait till the feature is further along and has more browser support before considering this, but thanks again for contributing!

---

Additionally, we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by pascalduez** [comment]
> Additionally, we require the template to be filled

IMO the other points were not making any sense to be filled.   
It aimed at preventing reviewers from loosing time, indeed :)

**Comment by Aerijo** [comment]
> It aimed at preventing reviewers from loosing time, indeed :)

@pascalduez While the thought is appreciated, too often we get issues and PR's that haven't filled out the template, and are lacking information needed to make it actionable / get a good review. It's normally better to let the reviewer decide what is needed, rather than guess and have them request it later anyway.

If something doesn't apply, e.g., Alternate Designs I tend to use NA. It shows that you explicitly decided it's not relevant, rather than just ignored the template (which happens all too frequently).

**Comment by pascalduez** [comment]
>  I tend to use NA

Good advice, thanks.

**Pull request closed without merging**
